# Generated by Django 3.2.8 on 2021-10-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='SpokenLanguages',
            field=models.IntegerField(choices=[(12, 'English'), (13, 'Chinese'), (14, 'Malay'), (15, 'Tamil'), (16, 'Hindi')], default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='familiarCodingLanguages',
            field=models.IntegerField(choices=[(7, 'Python'), (8, 'Java'), (9, 'Ruby'), (10, 'Javascript'), (11, 'Golang')], default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='favouriteColor',
            field=models.IntegerField(choices=[(1, 'Blue'), (2, 'Red'), (3, 'Green'), (4, 'Yellow'), (5, 'Purple'), (6, 'Pink')], default=1),
            preserve_default=False,
        ),
    ]
