# Generated by Django 3.2.8 on 2021-10-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20211030_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='SpokenLanguages',
            new_name='spokenLanguages',
        ),
    ]
