# Generated by Django 3.2.8 on 2021-10-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_rename_spokenlanguages_questionnaire_spokenlanguages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='familiarCodingLanguages',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='codingLanguage',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='favouriteColor',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='spokenLanguages',
            field=models.CharField(max_length=40),
        ),
    ]
