# Generated by Django 3.2.8 on 2021-10-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20211030_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='favouriteColor',
            new_name='favouriteColors',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='codingLanguage',
            new_name='programmingLanguage',
        ),
    ]
